name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Increment SemVer
      - name: Increment version
        id: semver
        run: |
          # Check if VERSION file exists
          if [ ! -f VERSION ]; then
            echo "0.0.0" > VERSION
          fi
          # Read the current version
          current_version=$(cat VERSION)
          # Increment the version (patch level)
          new_version=$(echo $current_version | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
          echo $new_version > VERSION
          echo "version=$new_version" >> $GITHUB_ENV

      # Commit the updated version
      - name: Commit updated version
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git commit -m "Increment version to ${{ env.version }}"
          git push

      # Build the project
      - name: Build the project
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          # Add the version to the commit message
          commit_message: 'Deploy version ${{ env.version }}'
